#!/bin/sh

CWD=`pwd`

PCB_DIR="./kicad/pcb"

java -jar ~/bin/./layout/opt/layout/bin/freeRouting.jar \
-dl -de ${PCB_DIR}/router.dsn -do ${PCB_DIR}/router.ses

#cd ../../bin/FreeRoutingNew/deploy/
# ./run.sh \
#-dl -de ${CWD}/kicad/router.dsn -do ${CWD}/kicad/router.ses


#cd ../../bin/
# java -jar freerouting-1.6.2.jar \
#-dl -de ${CWD}/kicad/router.dsn -do ${CWD}/kicad/router.ses

#cd ../../bin/
#java -jar freerouting-1.6.2.jar 
