stages:
    - test
    - build
    - release

image: registry.gitlab.com/alexives/keyboard_lib/openscad:latest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/

codequality:
  stage: test
  script:
    - make build sca2d
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

openspecad:
  stage: test
  parallel: 8
  script:
    - make test.ci
  artifacts:
    when: always
    reports:
      junit:
        - junit-$CI_NODE_INDEX.xml

commit:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
  stage: test
  image: alpine:latest
  script:
    - apk add git
    - git log $CI_MERGE_REQUEST_DIFF_BASE_SHA..$CI_MERGE_REQUEST_SOURCE_BRANCH_SHA | grep 'changelog:' && exit 1 || echo 'no bad changelog trailer'

commit needs changelog:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
  stage: test
  allow_failure: true
  image: alpine:latest
  script:
    - apk add git
    - git log $CI_MERGE_REQUEST_DIFF_BASE_SHA..$CI_MERGE_REQUEST_SOURCE_BRANCH_SHA | grep 'Changelog:'

build:
  except:
    - tags
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - keyboard_lib.*.scad
    expire_in: 1 week

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
  script:
    - apk add make curl git
    - make release
